pipeline {
    agent any

     environment {
         APP_IMAGE_REPOSITORY_NAME = 'devopsoh/api-poi'
         SRC_DIR = 'apis/poi'
    }

    stages {
        stage('Build') {
            steps {
               dir("${env.SRC_DIR}") {
                   sh 'dotnet build --configuration Release'
               }
            }
        }

        stage('Test') {
            steps {
               dir("${env.SRC_DIR}/tests/UnitTests") {
                   sh 'dotnet test "UnitTests.csproj" --no-restore --no-build --configuration Release'
               }
            }
        }

        stage('Open GitHub Issue') {
            steps {
                script {
                    properties([[$class: 'GithubProjectProperty',
                                projectUrlStr: 'https://github.com/vineet96/openhack-devops-team']])
                }

                step([$class: 'GitHubIssueNotifier',
                    issueAppend: true,
                    issueLabel: '',
                    issueTitle: '$JOB_NAME $BUILD_DISPLAY_NAME failed'])
            }
        }

        stage('Build Docker Image') {
           steps {
               dir("${env.SRC_DIR}/web") {
                   sh "docker build -t ${ACR_LOGINSERVER}/${env.APP_IMAGE_REPOSITORY_NAME}:${env.BUILD_NUMBER} ."
               }
           }
       }

       stage('Push Docker Image to Registry') {
           steps {
               dir("${env.SRC_DIR}/web") {
                   withDockerRegistry(credentialsId: 'acr-credentials', url: "https://${ACR_LOGINSERVER}") {
                       sh "docker push ${ACR_LOGINSERVER}/${env.APP_IMAGE_REPOSITORY_NAME}:${env.BUILD_NUMBER}"
                   }
               }
           }
       }
    }
}
